language: scala

jdk: oraclejdk9

scala:
   - 2.12.4

# Undo _JAVA_OPTIONS environment variable
before_script:
 - _JAVA_OPTIONS=

env:
 global:
  - TAP_HOSTS=localhost
  - JAVA_TOOL_OPTIONS="-Xms4g -Xmx6g"

script:
   - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx6g test

# Use container-based infrastructure
#sudo: false

# Virtual machine
sudo: required
dist: trusty

# These directories are cached to S3 at the end of the build
cache:
  directories:
     - $HOME/.ivy2/cache
     - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

#Testing build script